// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/activity/coupon": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "Issue coupon",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "issue coupon",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/go-micro_internal_activity.CouponRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/activity/seckill": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "Seckill request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "seckill request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/go-micro_internal_activity.SeckillRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/activity/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity"
                ],
                "summary": "Activity status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "coupon id",
                        "name": "coupon_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sku id",
                        "name": "sku_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_gateway.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/order-views/{order_no}": {
            "get": {
                "description": "view_status 为聚合层统一展示状态，优先级高于单一服务原始状态。\nview_status 枚举：PENDING、PROCESSING、SUCCESS、FAILED、DEAD、CANCELED、TIMEOUT。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "订单聚合视图",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "业务订单号",
                        "name": "order_no",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/orders": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "创建订单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "订单创建请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_gateway.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/orders/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "查询订单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "订单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/payments": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "创建支付",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建支付请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/go-micro_internal_payment.CreatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/payments/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "查询支付",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "支付ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/payments/{id}/failed": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "支付失败",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "支付ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/payments/{id}/success": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "支付成功",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "支付ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/payments/{id}/timeout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "支付超时",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "支付ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/price/calculate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Price"
                ],
                "summary": "Calculate price",
                "parameters": [
                    {
                        "description": "calculate price",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_price.CalculateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/price/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Price"
                ],
                "summary": "Price history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "sku id",
                        "name": "sku_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/refund/initiate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Refund"
                ],
                "summary": "Initiate refund",
                "parameters": [
                    {
                        "description": "initiate refund",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_refund.InitiateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/refund/rollback": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Refund"
                ],
                "summary": "Rollback on cancel",
                "parameters": [
                    {
                        "description": "rollback refund",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_refund.RollbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/refund/status": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Refund"
                ],
                "summary": "Refund status",
                "parameters": [
                    {
                        "description": "refund status",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_refund.StatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取当前用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/inventory/confirm": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "summary": "确认扣减",
                "parameters": [
                    {
                        "description": "确认请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_inventory.ConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/inventory/release": {
            "post": {
                "description": "基于 reserved_id 释放，重复调用幂等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "summary": "释放库存",
                "parameters": [
                    {
                        "description": "释放请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_inventory.ReleaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/inventory/release-by-order": {
            "post": {
                "description": "基于订单号幂等释放库存，重复调用不会重复回补",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "summary": "按订单号释放",
                "parameters": [
                    {
                        "description": "订单号释放请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_inventory.ReleaseByOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/inventory/reservations/{order_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "summary": "查询预占记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单ID",
                        "name": "order_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/inventory/reserve": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "summary": "预占库存",
                "parameters": [
                    {
                        "description": "预占请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_inventory.ReserveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/inventory/{sku_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inventory"
                ],
                "summary": "查询库存",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SKU ID",
                        "name": "sku_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/orders": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "创建订单",
                "parameters": [
                    {
                        "description": "创建订单请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_order.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/orders/biz/{biz_no}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "按业务单号查询",
                "parameters": [
                    {
                        "type": "string",
                        "description": "业务订单号",
                        "name": "biz_no",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/orders/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "查询订单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/orders/{id}/cancel": {
            "post": {
                "description": "幂等语义：已取消返回成功，已完成不可取消",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "取消订单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/payments": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "创建支付",
                "parameters": [
                    {
                        "description": "创建支付请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_payment.CreatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/payments/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "查询支付",
                "parameters": [
                    {
                        "type": "string",
                        "description": "支付ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/payments/{id}/failed": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "支付失败",
                "parameters": [
                    {
                        "type": "string",
                        "description": "支付ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/payments/{id}/refund": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "退款",
                "parameters": [
                    {
                        "type": "string",
                        "description": "支付ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/payments/{id}/success": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "支付成功",
                "parameters": [
                    {
                        "type": "string",
                        "description": "支付ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/payments/{id}/timeout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payment"
                ],
                "summary": "支付超时",
                "parameters": [
                    {
                        "type": "string",
                        "description": "支付ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "创建任务",
                "parameters": [
                    {
                        "description": "创建任务请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_task.CreateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/tasks/by-order/{order_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "按订单查询任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "订单ID",
                        "name": "order_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "查询任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/tasks/{id}/retry": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "手动重试任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "description": "用户创建请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_user.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "查询用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-micro_pkg_httpx.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "go-micro_internal_activity.CouponRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "coupon_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "go-micro_internal_activity.SeckillRequest": {
            "type": "object",
            "properties": {
                "quantity": {
                    "type": "integer"
                },
                "sku_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "go-micro_internal_payment.CreatePaymentRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "go-micro_internal_price.CalculateRequest": {
            "type": "object",
            "properties": {
                "base_price": {
                    "type": "number"
                },
                "coupon_amount": {
                    "type": "number"
                },
                "sku_id": {
                    "type": "string"
                },
                "user_level": {
                    "type": "integer"
                }
            }
        },
        "go-micro_internal_refund.InitiateRequest": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "refund_id": {
                    "type": "string"
                },
                "refund_type": {
                    "type": "string"
                }
            }
        },
        "go-micro_internal_refund.RollbackRequest": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "refund_id": {
                    "type": "string"
                }
            }
        },
        "go-micro_internal_refund.StatusRequest": {
            "type": "object",
            "properties": {
                "refund_id": {
                    "type": "string"
                }
            }
        },
        "go-micro_pkg_httpx.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_activity.CouponRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "coupon_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_activity.SeckillRequest": {
            "type": "object",
            "properties": {
                "quantity": {
                    "type": "integer"
                },
                "sku_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_gateway.CreateOrderRequest": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_gateway.Item"
                    }
                },
                "remark": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_gateway.Item": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "sku_id": {
                    "type": "string"
                }
            }
        },
        "internal_gateway.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_inventory.ConfirmRequest": {
            "type": "object",
            "properties": {
                "reserved_id": {
                    "type": "string"
                }
            }
        },
        "internal_inventory.Item": {
            "type": "object",
            "properties": {
                "quantity": {
                    "type": "integer"
                },
                "sku_id": {
                    "type": "string"
                }
            }
        },
        "internal_inventory.ReleaseByOrderRequest": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "string"
                }
            }
        },
        "internal_inventory.ReleaseRequest": {
            "type": "object",
            "properties": {
                "reserved_id": {
                    "type": "string"
                }
            }
        },
        "internal_inventory.ReserveRequest": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_inventory.Item"
                    }
                },
                "order_id": {
                    "type": "string"
                }
            }
        },
        "internal_order.CreateOrderRequest": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_order.Item"
                    }
                },
                "remark": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_order.Item": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "sku_id": {
                    "type": "string"
                }
            }
        },
        "internal_payment.CreatePaymentRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "internal_price.CalculateRequest": {
            "type": "object",
            "properties": {
                "base_price": {
                    "type": "number"
                },
                "coupon_amount": {
                    "type": "number"
                },
                "sku_id": {
                    "type": "string"
                },
                "user_level": {
                    "type": "integer"
                }
            }
        },
        "internal_refund.InitiateRequest": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "refund_id": {
                    "type": "string"
                },
                "refund_type": {
                    "type": "string"
                }
            }
        },
        "internal_refund.RollbackRequest": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "refund_id": {
                    "type": "string"
                }
            }
        },
        "internal_refund.StatusRequest": {
            "type": "object",
            "properties": {
                "refund_id": {
                    "type": "string"
                }
            }
        },
        "internal_task.CreateTaskRequest": {
            "type": "object",
            "properties": {
                "biz_no": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "internal_user.CreateUserRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go-Micro Gateway API",
	Description:      "Go-Micro 网关服务 API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	
	
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
