# syntax=docker/dockerfile:1
FROM golang:1.25 AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/price ./cmd/price-service

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /out/price /app/price
EXPOSE 8088 9088
CMD ["/app/price"]
