# syntax=docker/dockerfile:1
FROM golang:1.25 AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/order ./cmd/order-service

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /out/order /app/order
EXPOSE 8081 9081
CMD ["/app/order"]
