# syntax=docker/dockerfile:1
FROM golang:1.22 AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/user ./cmd/user-service

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /out/user /app/user
EXPOSE 8083
CMD ["/app/user"]
